#
# Your Crowdin credentials
#
"project_id_env" : "CROWDIN_PROJECT_ID"
"api_token_env" : "CROWDIN_PERSONAL_TOKEN"
"base_path" : "."
"base_url" : "https://api.crowdin.com"

#
# Choose file structure in Crowdin
# e.g. true or false
#
"preserve_hierarchy": true
#
# Files configuration
#
files: [
# Files
  {
    "source" : "/notes-service/src/main/resources/locale/wiki/service/WikiService_en.properties",

    "translation" : "%original_path%/%file_name%!_%locale_with_underscore%.%file_extension%",
    "translation_replace" : {YML_CROWDIN_LANGUAGES_ARG},
    "dest" : "hub/notes/service/WikiService.properties",
    "update_option" : "update_as_unapproved",
    "escape_special_characters": 0,
    "escape_quotes" : 0,
  },
  {
    "source" : "/notes-social-integration/src/main/resources/locale/wiki/integration/integration_en.properties",

    "translation" : "%original_path%/%file_name%!_%locale_with_underscore%.%file_extension%",
    "translation_replace" : {YML_CROWDIN_LANGUAGES_ARG},
    "dest" : "hub/notes/service/integration.properties",
    "update_option" : "update_as_unapproved",
    "escape_special_characters": 0,
    "escape_quotes" : 0,
  },
  {
    "source" : "/notes-webapp/src/main/resources/locale/portal/webui_en.properties",

    "translation" : "%original_path%/%file_name%!_%locale_with_underscore%.%file_extension%",
    "translation_replace" : {YML_CROWDIN_LANGUAGES_ARG},
    "dest" : "hub/notes/webapp/webui.properties",
    "update_option" : "update_as_unapproved",
    "escape_special_characters": 0,
    "escape_quotes" : 0,
  },
  {
    "source" : "/notes-webapp/src/main/resources/locale/portlet/wiki/WikiPortlet_en.properties",

    "translation" : "%original_path%/%file_name%!_%locale_with_underscore%.%file_extension%",
    "translation_replace" : {YML_CROWDIN_LANGUAGES_ARG},
    "dest" : "hub/notes/webapp/WikiPortlet.properties",
    "update_option" : "update_as_unapproved",
    "escape_special_characters": 0,
    "escape_quotes" : 0,
  },
  {
    "source" : "/notes-webapp/src/main/resources/locale/portlet/notes/notesPortlet_en.properties",

    "translation" : "%original_path%/%file_name%!_%locale_with_underscore%.%file_extension%",
    "translation_replace" : {YML_CROWDIN_LANGUAGES_ARG},
    "dest" : "hub/notes/webapp/NotesPortlet.properties",
    "update_option" : "update_as_unapproved",
    "escape_special_characters": 0,
    "escape_quotes" : 0,
  },
  {
    "source" : "/notes-webapp/src/main/resources/locale/portlet/Portlets_en.properties",

    "translation" : "%original_path%/%file_name%!_%locale_with_underscore%.%file_extension%",
    "translation_replace" : {YML_CROWDIN_LANGUAGES_ARG},
    "dest" : "hub/notes/webapp/Portlet.properties",
    "update_option" : "update_as_unapproved",
    "escape_special_characters": 0,
    "escape_quotes" : 0,
  },
  {
    "source" : "/notes-webapp/src/main/resources/locale/portlet/NotePageView_en.properties",

    "translation" : "%original_path%/%file_name%!_%locale_with_underscore%.%file_extension%",
    "translation_replace" : {YML_CROWDIN_LANGUAGES_ARG},
    "dest" : "hub/notes/webapp/NotePageView.properties",
    "update_option" : "update_as_unapproved",
    "escape_special_characters": 0,
    "escape_quotes" : 0,
  },
  {
    "source": "/notes-webapp/src/main/resources/locale/portlet/TermsAndConditionsView_en.properties",

    "translation": "%original_path%/%file_name%!_%locale_with_underscore%.%file_extension%",
    "translation_replace" : {YML_CROWDIN_LANGUAGES_ARG},
    "dest": "hub/notes/webapp/TermsAndConditionsView.properties",
    "update_option": "update_as_unapproved",
    "escape_special_characters": 0,
    "escape_quotes": 0,
  },
  {
    "source": "/notes-webapp/src/main/resources/locale/portlet/GeneralSettings_en.properties",

    "translation": "%original_path%/%file_name%!_%locale_with_underscore%.%file_extension%",
    "translation_replace" : {YML_CROWDIN_LANGUAGES_ARG},
    "dest": "hub/notes/webapp/GeneralSettings.properties",
    "update_option": "update_as_unapproved",
    "escape_special_characters": 0,
    "escape_quotes": 0,
  },
  # Portal
  {
    "source" : "/notes-webapp/src/main/resources/locale/navigation/portal/global_en.properties",

    "translation" : "%original_path%/%file_name%!_%locale_with_underscore%.%file_extension%",
    "translation_replace" : {YML_CROWDIN_LANGUAGES_ARG},
    "dest" : "hub/notes/portal/global.properties",
    "update_option" : "update_as_unapproved",
    "escape_special_characters": 0,
    "escape_quotes" : 0,
  },
  # Analytics
  {
    "source" : "/notes-webapp/src/main/resources/locale/portlet/Analytics_en.properties",

    "translation" : "%original_path%/%file_name%!_%locale_with_underscore%.%file_extension%",
    "translation_replace" : {YML_CROWDIN_LANGUAGES_ARG},
    "dest" : "hub/notes/Analytics.properties",
    "update_option" : "update_as_unapproved",
    "escape_special_characters": 0,
    "escape_quotes" : 0,
  },
  {
    "source" : "/notes-webapp/src/main/resources/locale/addon/Gamification_en.properties",

    "translation" : "%original_path%/%file_name%!_%locale_with_underscore%.%file_extension%",
    "translation_replace" : {YML_CROWDIN_LANGUAGES_ARG},
    "dest" : "hub/notes/Gamification.properties",
    "update_option" : "update_as_unapproved",
    "escape_special_characters": 0,
    "escape_quotes" : 0,
  },
  {
    "source" : "/notes-webapp/src/main/resources/locale/portlet/LayoutEditor_en.properties",

    "translation" : "%original_path%/%file_name%!_%locale_with_underscore%.%file_extension%",
    "translation_replace" : {YML_CROWDIN_LANGUAGES_ARG},
    "dest" : "hub/notes/LayoutEditor.properties",
    "update_option" : "update_as_unapproved",
    "escape_special_characters": 0,
    "escape_quotes" : 0,
  },
  {
    "source" : "/notes-webapp/src/main/resources/locale/portlet/ContentLink_en.properties",

    "translation" : "%original_path%/%file_name%!_%locale_with_underscore%.%file_extension%",
    "translation_replace" : {YML_CROWDIN_LANGUAGES_ARG},
    "dest" : "hub/notes/ContentLink.properties",
    "update_option" : "update_as_unapproved",
    "escape_special_characters": 0,
    "escape_quotes" : 0,
  },
]
